---
title: "exploratory_data_analysis"
author: "Jill Cates"
date: '2017-11-27'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(maps)
```

```{r}
usa <- map_data("usa")
canada <- map_data("world", "canada")
states <- map_data("state")
north_america <- ggplot() + geom_polygon(data=states, aes(x = long, y = lat, group = group), color = "white", size=0.15, fill="#7f7f7f") + geom_polygon(data=canada, aes(x=long, y=lat, group = group), fill="#7f7f7f") +theme_classic() + coord_fixed(1.3)


```

```{r}
cities <- data.frame(
  city = c("San Francisco", "Toronto", "Los Angeles", "Vancouver", "Seattle", "San Diego", "New York", "Washington DC", "Chicago", "Las Vegas", "Boston", "Houston", "Portland", "Atlanta", "Philadelphia", "Phoenix", "Miami", "Denver", "Dallas", "Charlotte", "Minneapolis", "Montreal"),
  lat = c(37.773972, 43.639217, 34.052235, 49.246292, 47.608013, 32.715736, 40.730610, 38.930176, 41.881832, 36.114647, 42.361145, 29.759438, 45.523064, 33.753746, 39.952583, 33.448376, 25.761681, 39.742043, 32.897480, 35.227085, 44.986656, 45.5017),
  long = c(-122.431297, -79.400414, -118.243683, -123.116226, -122.335167, -117.161087, -73.935242, -77.070503, -87.623177, -115.172813, -71.057083, -95.369957, -122.676483, -84.386330, -75.165222, -112.074036, -80.191788, -104.991531, -97.040443, -80.843124, -93.258133, -73.5673),
  stringsAsFactors = FALSE
)

north_america + 
  geom_point(data=cities, aes(x = long, y = lat), color="red", size = 1) + theme(legend.position="none") + ggtitle("North American Cities with Ramen and Pho Restaurants")

ggsave("../../results/north_america_map.png", width = 20, height = 20, units = "cm")
```


