digraph G {
n2[label="all", color="red"];
n3[label="doc/report.md", color="green"];
n7[label="results/pho_popularity.png", color="green"];
n5[label="results/ramen_pho_restaurants_by_city.png", color="green"];
n6[label="results/ramen_popularity.png", color="green"];
n4[label="src/report.Rmd", color="green"];
n3 -> n2 ; 
n7 -> n3 ; 
n5 -> n3 ; 
n6 -> n3 ; 
n4 -> n3 ; 
}
